[development]
address = "sikora-laptop.local"
port = 8000
workers = 24
log = "normal"
limits = { forms = 32768 }
[production]
address = "0.0.0.0"
port = 8000
log = "normal"
limits = { forms = 32768 }
