[development]
address = "sikora-laptop.local"
port = 8000
workers = 24
log = "normal"
limits = { forms = 32768 }
[production]
address = "sikora-laptop.local"
port = 22070
log = "normal"
limits = { forms = 32768 }
