[development]
# address = "sikora-laptop.local"
address = "0.0.0.0"
port = 8000
workers = 24
log = "normal"
limits = { forms = 32768 }
[global]
# address = "sikora-laptop.local"
address = "0.0.0.0"
port = 8000
workers = 24
log = "normal"
limits = { forms = 32768 }
